accounts/urls.py
from django.urls import path, include
from accounts import views as v
# from app.views import TaskList,TaskDetial,CreateTask
urlpatterns = [
    # path('',include('django.contrib.auth.urls'),name='authurls'),
    path('login/',v.Login.as_view(),name='login'),
    path('logout/',v.Logout.as_view(),name='logout'),
    path('register/',v.Register.as_view(),name='register'),
]

app/urls.py
from django.urls import path
from app import views as v
# from app.views import TaskList,TaskDetial,CreateTask
urlpatterns = [
    path('home',v.index,name='home'),
    path('tasks',v.TaskList.as_view(),name='tasklist'),
    path('task/<int:pk>',v.TaskDetial.as_view(),name='taskdetial'),
    path('create',v.CreateTask.as_view(),name='createtask'),
    path('update/<int:pk>',v.UpdateTask.as_view(),name='updatetask'),
    path('delete/<int:pk>',v.DeleteTask.as_view(),name='deletetask'),
]

todo/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'), name='todo'),
    path('acc/', include('accounts.urls'), name='todo'),
]

accounts/models.py
from django.db import models

# Create your models here.

app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Task(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    title = models.CharField(max_length=200,default='task one')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return self.title
    
    class Meta:
        ordering =['completed']

accounts/views.py
from django.shortcuts import render 
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView ,LogoutView
from django.views.generic import FormView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login


class Login(LoginView):
    next_page = reverse_lazy('home')

class Logout(LogoutView):
    next_page = reverse_lazy('login')

class Register(FormView):
    template_name = 'registration/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    def form_valid(self, form):
        user=form.save()
        if user is not None:
            login(self.request,user)
        return super(Register,self).form_valid(form)

app/views.py
# from django.http import 
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView ,ListView , DetailView , UpdateView , DeleteView
from app.models import Task
from django.contrib.auth.mixins import LoginRequiredMixin


def index(request):
    if request.method == 'GET':
        tasks = Task.objects.filter(user=request.user)
        # print(Task.objects.filter(user=request.user))
        # print(request.user)
        # print(tasks)
    context = {'object_list':tasks}
    print(tasks)
    return render(request,'app/index.html',context)


class CreateTask(LoginRequiredMixin,CreateView):
    model = Task
    fields = ['title']
    # template_name = 'app/index.html'
    # tasks = Task.objects.all()
    # context = {'tasks':tasks}
    # queryset = tasks
    success_url = reverse_lazy('home')

class TaskList(LoginRequiredMixin,ListView):
    model = Task
    context_object_name = 'tasks'
    def get_context_data(self, **kwargs) -> dict[str, any]:
        context = super().get_context_data(**kwargs)
        context["tasks"] = context["tasks"].filter(user=self.request.user)
        print(context)
        return context


class TaskDetial(LoginRequiredMixin,DetailView):
    model = Task
    context_object_name = 'task'
    # template_name = '' # u can change the template name not strict !!

class UpdateTask(UpdateView):
    model = Task
    template_name = 'app/task_update.html'
    context_object_name ='task'
    fields = ['title']
    success_url = reverse_lazy('home')

class DeleteTask(DeleteView):
    model = Task
    context_object_name = 'task'
    success_url = reverse_lazy('home')

app/templates/test.html
<h1> klasdjfklasdjfkljkl </h1>

templates/app/index.html
{% extends "base.html" %}

{% block content %}
{{request.user}}

{% include "app/task_list.html" %}
{% endblock content %}

templates/app/task_confirm_delete.html
{% include "bootstrap.html" %}
<h1> dflkak</h1>
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-title">Confirmation Page</h2>
                    <form method='post'>
                        {% csrf_token %}
                    <p class="card-text">Are you sure you want to delete {{task}}?</p>
                    <input href="" class="btn btn-success" type='submit' value='Yes, Proceed'>
                    <a href={% url "home" %} class="btn btn-danger">No, Cancel</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

templates/app/task_detail.html
<h1> detial </h1>
{{task.title}}
{{task.title}}
{{task.title}}
{{task.title}}

templates/app/task_form.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="post">
                {% csrf_token %}
                {{form}}
                <input type="submit" class="btn btn-primary" value="Create Task">
            </form>
        </div>
    </div>
</div>


<script src="{% static 'js/script.js' %}"></script>
{% endblock content %}

templates/app/task_list.html
{% comment %} {% extends "base.html" %} {% endcomment %}

{% block content %}
<div class="container">
    <h1>Task List</h1>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Title</th>
                <th>Description</th>
                <th>Created At</th>
                <th>Completed</th>
            </tr>
        </thead>
        <tbody>
            {% for task in object_list %}
            <tr>
                <td>{{ task.title }}</td>
                <td>{{ task.description }}</td>
                <td>{{ task.created_at }}</td>
                <td>{{ task.completed }}</td>
                <td><a class='btn btn-warning' href={% url "updatetask" task.id %}>update</a></td>
                <td><a class='btn btn-danger' href={% url "deletetask" task.id %}>Delete</a></td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="3">No tasks found.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

templates/app/task_update.html
{% extends "base.html" %}
{% load static %}
<h1> update</h1>

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="post">
                {% csrf_token %}
                {{form}}
                <input type="submit" class="btn btn-primary" value="update Task">
            </form>
        </div>
    </div>
</div>


<script src="{% static 'js/script.js' %}"></script>
{% endblock content %}

templates/app/test.html
<h1> test </h1>

templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% comment %} cnd for bootstarp {% endcomment %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.2/js/bootstrap.min.js" ></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.2/css/bootstrap.min.css">
    {% comment %}  {% endcomment %}
    <title> {% block title %}{% endblock title %} </title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-warning">
        <a class="navbar-brand" href={% url "home" %}>Amazon</a>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="">Products</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="">Contact Us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="">About Us</a>
                </li>
            </ul>
            <div class='bg-secondary text-light'>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link text-light" href={% url "createtask" %}>Add Task</a>
                </li>
                </li>
            </ul>
        </div>
        <a class='btn btn-dark m-2' href= {% url "tasklist" %}>All Tasks</a>
        {% if request.user.is_authenticated%}
        <a class="btn btn-danger m-2" href={% url "logout" %} >Logout</a>
        {% else %}
        <a class="btn btn-success m-2" href={% url "login" %} >Login</a>
        <a class="btn btn-primary" href={% url "register" %}>Register</a>
        {% endif %}
        </div>
        <form method="post"  action="">
            {% csrf_token %}
        <div class="d-flex justify-content-start">
            <div class="input-group">
                <input type="text" name='search_term' class="form-control" placeholder="Search">
                <div class="input-group-append">
                <button class="btn btn-primary" type="submit">Search</button>
                </div>
            </div>
            </div>
        </form>
    </nav>

    {% block content %}
    {% endblock content %}

</body>
</html>

templates/bootstrap.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% comment %} cnd for bootstarp {% endcomment %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.2/js/bootstrap.min.js" ></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.2/css/bootstrap.min.css">
    {% comment %}  {% endcomment %}
    <title> {% block title %}{% endblock title %} </title>
</head>